### ISSUE TITLE
rename components as categories to match Andrew's nomenclature. 

### ISSUE THREAD

**Issue by hschellman** [MinervaExpt/CCQENu#15]
Should we rename components as categories to match Andrew's notation. 

Change it in code but make the code accept both component and category on inputs.

**Comment by smgilligan** [comment]
Renamed 'component', 'components', 'Component', and 'Components' to 'category', 'categories'. 'Category', and 'Categories' respectively. Limited testing performed. Changes pushed to main. Issue closed until further notice.
