### ISSUE TITLE
Add background/signal fraction rewieight

### ISSUE THREAD

**Issue by nhvaughan** [MinervaExpt/CCQENu#8]
What needs to happen:

- [x] Test `FractionFitTest.py` works with new version.
- [x] Add Systematics to fraction fitter & test with MnvViewer
- [x] Create reweighter class that applies scale factor fit to copies of MC distributions and implement in `sidebands.C`
- [x] Check for closure by confirming minimal correction needed in `FractionFitTest.py`
- [x] Implement corrected MC distributions for signal fraction in `GetXSec.h`
- [x] Make a component test for the weighting function.  

Other options that might be useful:

- [x] Add to main config which fit to use (stored in a `.root` file) and which distributions to add it to

**Comment by nhvaughan** [comment]
New fit script is `make_hists/nhv/bkgfitting/FractionFitWithSystematics.py`  #16 . It is a little different and doesn't do any of the plotting. Might be good to:

- [ ] add storage of recoil hist fits to this new script and create a separate plotting script for future use.

**Comment by hschellman** [comment]
You definitely need to store the outputs, including the before and after fit histograms.

**Comment by nhvaughan** [comment]
- Need to check on how reweighters are being implemented. 
- Set up so this gets switched on and off in config.
- Set so reweight only gets used on MC reco if doing the MC reweighting; or data if doing data reweighting. (Maybe have a switch to also handle that choice?)
